/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
import { LinkInfo } from "./components/link-box/link-box";
import { GroupInfo } from "./components/link-group/link-group";
import { VisibleInfo } from "./components/link-modal/link-modal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface LinkBox {
        "link": LinkInfo;
    }
    interface LinkGroup {
        "group": GroupInfo;
    }
    interface LinkModal {
        "visible": VisibleInfo;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLinkBoxElement extends Components.LinkBox, HTMLStencilElement {
    }
    var HTMLLinkBoxElement: {
        prototype: HTMLLinkBoxElement;
        new (): HTMLLinkBoxElement;
    };
    interface HTMLLinkGroupElement extends Components.LinkGroup, HTMLStencilElement {
    }
    var HTMLLinkGroupElement: {
        prototype: HTMLLinkGroupElement;
        new (): HTMLLinkGroupElement;
    };
    interface HTMLLinkModalElement extends Components.LinkModal, HTMLStencilElement {
    }
    var HTMLLinkModalElement: {
        prototype: HTMLLinkModalElement;
        new (): HTMLLinkModalElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "link-box": HTMLLinkBoxElement;
        "link-group": HTMLLinkGroupElement;
        "link-modal": HTMLLinkModalElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface LinkBox {
        "link"?: LinkInfo;
        "onEditLinkEvent"?: (event: CustomEvent<any>) => void;
    }
    interface LinkGroup {
        "group"?: GroupInfo;
        "onUpdateGroup"?: (event: CustomEvent<any>) => void;
    }
    interface LinkModal {
        "onCloseLinkModal"?: (event: CustomEvent<any>) => void;
        "onSaveLinkModal"?: (event: CustomEvent<any>) => void;
        "visible"?: VisibleInfo;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "link-box": LinkBox;
        "link-group": LinkGroup;
        "link-modal": LinkModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "link-box": LocalJSX.LinkBox & JSXBase.HTMLAttributes<HTMLLinkBoxElement>;
            "link-group": LocalJSX.LinkGroup & JSXBase.HTMLAttributes<HTMLLinkGroupElement>;
            "link-modal": LocalJSX.LinkModal & JSXBase.HTMLAttributes<HTMLLinkModalElement>;
        }
    }
}
